export const primaryColor = "#0671d0"
export const warningColor = "#ffe200"
export const dangerColor = "#ff0000"
export const defaultBgColor = "#ababab"
export const black = "#000"
export const white = "#fff"